// This file was autogenerated by C:/Users/5/Dropbox/javascript/CloverJS-WorkSpace/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../cloverjs/clover/clover/clover.js', ['clover'], []);
goog.addDependency('../../../cloverjs/clover/clover/ui/scaffolding/abstractlayout.js', ['clover.ui.scaffolding.AbstractLayout'], ['goog.dom.ViewportSizeMonitor', 'goog.events.EventHandler', 'goog.events.EventType', 'goog.ui.Component', 'goog.ui.registry']);
goog.addDependency('../../../cloverjs/clover/clover/ui/scaffolding/abstractlayoutrenderer.js', ['clover.ui.scaffolding.AbstractLayoutRenderer'], []);
goog.addDependency('../../../cloverjs/clover/clover/ui/scaffolding/fixedlayout.js', ['clover.ui.scaffolding.AbstractFixedLayoutRenderer', 'clover.ui.scaffolding.FixedLayout', 'clover.ui.scaffolding.FixedLayoutRenderer'], ['clover.ui.scaffolding.AbstractLayout', 'clover.ui.scaffolding.AbstractLayoutRenderer', 'goog.ui.registry']);
goog.addDependency('../../../cloverjs/clover/clover/ui/scaffolding/fluidlayout.js', ['clover.ui.scaffolding.AbstractFluidLayoutRenderer', 'clover.ui.scaffolding.FluidLayout', 'clover.ui.scaffolding.FluidLayoutRenderer'], ['clover.ui.scaffolding.AbstractLayout', 'clover.ui.scaffolding.AbstractLayoutRenderer', 'goog.ui.registry']);
goog.addDependency('../../../cloverjs/clover/clover/ui/scaffolding/scaffolding.js', ['clover.ui.scaffolding'], []);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/Button.js', ['bootstrap.Button'], ['bootstrap.ButtonRenderer', 'goog.ui.Button']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/ButtonRenderer.js', ['bootstrap.ButtonRenderer'], ['goog.ui.NativeButtonRenderer', 'goog.ui.registry']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/Dialog.js', ['bootstrap.Dialog'], ['goog.ui.Dialog']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/Pills.js', ['bootstrap.Pills'], ['bootstrap.PillsRenderer', 'goog.ui.TabBar']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/PillsRenderer.js', ['bootstrap.PillsRenderer'], ['bootstrap.TabBarRenderer', 'goog.ui.registry']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/Tab.js', ['bootstrap.Tab'], ['bootstrap.TabRenderer', 'goog.ui.Tab']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/TabBarRenderer.js', ['bootstrap.TabBarRenderer'], ['goog.ui.TabBarRenderer']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/TabRenderer.js', ['bootstrap.TabRenderer'], ['goog.ui.TabRenderer', 'goog.ui.registry']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/Tabs.js', ['bootstrap.Tabs'], ['bootstrap.TabsRenderer', 'goog.ui.TabBar']);
goog.addDependency('../../../cloverjs/third_party/closure-bootsrtap/javascript/bootstrap/TabsRenderer.js', ['bootstrap.TabsRenderer'], ['bootstrap.TabBarRenderer', 'goog.ui.registry']);
