// This script licensed under the MIT.
// http://orgachem.mit-license.org

/**
 * @fileoverview Script for Available icon types.
 * @author orga.chem.job@gmail.com (Orga Chem)
 */

goog.provide('clover.ui.icon.IconType');



/**
 * Available Icon classes.
 *
 * Glyphicons: 
 * http://glyphicons.com/
 *
 * This icons licensed under CC BY-ND 3.0.
 * http://creativecommons.org/licenses/by-nd/3.0/
 * @enum {string}
 */
clover.ui.icon.IconType = {
  GLASS: goog.getCssName('icon-glass'),
  MUSIC: goog.getCssName('icon-music'),
  SEARCH: goog.getCssName('icon-search'),
  ENVELOPE: goog.getCssName('icon-envelope'),
  HEART: goog.getCssName('icon-heart'),
  STAR: goog.getCssName('icon-star'),
  STAR_EMPTY: goog.getCssName('icon-star-empty'),
  USER: goog.getCssName('icon-user'),
  FILM: goog.getCssName('icon-film'),
  TH_LARGE: goog.getCssName('icon-th-large'),
  TH: goog.getCssName('icon-th'),
  TH_LIST: goog.getCssName('icon-th-list'),
  OK: goog.getCssName('icon-ok'),
  REMOVE: goog.getCssName('icon-remove'),
  ZOOM_IN: goog.getCssName('icon-zoom-in'),
  ZOOM_OUT: goog.getCssName('icon-zoom-out'),
  OFF: goog.getCssName('icon-off'),
  SIGNAL: goog.getCssName('icon-signal'),
  COG: goog.getCssName('icon-cog'),
  TRASH: goog.getCssName('icon-trash'),
  HOME: goog.getCssName('icon-home'),
  FILE: goog.getCssName('icon-file'),
  TIME: goog.getCssName('icon-time'),
  ROAD: goog.getCssName('icon-road'),
  DOWNLOAD_ALT: goog.getCssName('icon-download-alt'),
  DOWNLOAD: goog.getCssName('icon-download'),
  UPLOAD: goog.getCssName('icon-upload'),
  INBOX: goog.getCssName('icon-inbox'),
  PLAY_CIRCLE: goog.getCssName('icon-play-circle'),
  REPEAT: goog.getCssName('icon-repeat'),
  REFRESH: goog.getCssName('icon-refresh'),
  LIST_ALT: goog.getCssName('icon-list-alt'),
  LOCK: goog.getCssName('icon-lock'),
  FLAG: goog.getCssName('icon-flag'),
  HEADPHONES: goog.getCssName('icon-headphones'),
  VOLUME_OFF: goog.getCssName('icon-volume-off'),
  VOLUME_DOWN: goog.getCssName('icon-volume-down'),
  VOLUME_UP: goog.getCssName('icon-volume-up'),
  QRCODE: goog.getCssName('icon-qrcode'),
  BARCODE: goog.getCssName('icon-barcode'),
  TAG: goog.getCssName('icon-tag'),
  TAGS: goog.getCssName('icon-tags'),
  BOOK: goog.getCssName('icon-book'),
  BOOKMARK: goog.getCssName('icon-bookmark'),
  PRINT: goog.getCssName('icon-print'),
  CAMERA: goog.getCssName('icon-camera'),
  FONT: goog.getCssName('icon-font'),
  BOLD: goog.getCssName('icon-bold'),
  ITALIC: goog.getCssName('icon-italic'),
  TEXT_HEIGHT: goog.getCssName('icon-text-height'),
  TEXT_WIDTH: goog.getCssName('icon-text-width'),
  ALIGN_LEFT: goog.getCssName('icon-align-left'),
  ALIGN_CENTER: goog.getCssName('icon-align-center'),
  ALIGN_RIGHT: goog.getCssName('icon-align-right'),
  ALIGN_JUSTIFY: goog.getCssName('icon-align-justify'),
  LIST: goog.getCssName('icon-list'),
  INDENT_LEFT: goog.getCssName('icon-indent-left'),
  INDENT_RIGHT: goog.getCssName('icon-indent-right'),
  FACETIME_VIDEO: goog.getCssName('icon-facetime-video'),
  PICTURE: goog.getCssName('icon-picture'),
  PENCIL: goog.getCssName('icon-pencil'),
  MAP_MARKER: goog.getCssName('icon-map-marker'),
  ADJUST: goog.getCssName('icon-adjust'),
  TINT: goog.getCssName('icon-tint'),
  EDIT: goog.getCssName('icon-edit'),
  SHARE: goog.getCssName('icon-share'),
  CHECK: goog.getCssName('icon-check'),
  MOVE: goog.getCssName('icon-move'),
  STEP_BACKWARD: goog.getCssName('icon-step-backward'),
  FAST_BACKWARD: goog.getCssName('icon-fast-backward'),
  BACKWARD: goog.getCssName('icon-backward'),
  PLAY: goog.getCssName('icon-play'),
  PAUSE: goog.getCssName('icon-pause'),
  STOP: goog.getCssName('icon-stop'),
  FORWARD: goog.getCssName('icon-forward'),
  FAST_FORWARD: goog.getCssName('icon-fast-forward'),
  STEP_FORWARD: goog.getCssName('icon-step-forward'),
  EJECT: goog.getCssName('icon-eject'),
  CHEVRON_LEFT: goog.getCssName('icon-chevron-left'),
  CHEVRON_RIGHT: goog.getCssName('icon-chevron-right'),
  PLUS_SIGN: goog.getCssName('icon-plus-sign'),
  MINUS_SIGN: goog.getCssName('icon-minus-sign'),
  REMOVE_SIGN: goog.getCssName('icon-remove-sign'),
  OK_SIGN: goog.getCssName('icon-ok-sign'),
  QUESTION_SIGN: goog.getCssName('icon-question-sign'),
  INFO_SIGN: goog.getCssName('icon-info-sign'),
  SCREENSHOT: goog.getCssName('icon-screenshot'),
  REMOVE_CIRCLE: goog.getCssName('icon-remove-circle'),
  OK_CIRCLE: goog.getCssName('icon-ok-circle'),
  BAN_CIRCLE: goog.getCssName('icon-ban-circle'),
  ARROW_LEFT: goog.getCssName('icon-arrow-left'),
  ARROW_RIGHT: goog.getCssName('icon-arrow-right'),
  ARROW_UP: goog.getCssName('icon-arrow-up'),
  ARROW_DOWN: goog.getCssName('icon-arrow-down'),
  SHARE_ALT: goog.getCssName('icon-share-alt'),
  RESIZE_FULL: goog.getCssName('icon-resize-full'),
  RESIZE_SMALL: goog.getCssName('icon-resize-small'),
  PLUS: goog.getCssName('icon-plus'),
  MINUS: goog.getCssName('icon-minus'),
  ASTERISK: goog.getCssName('icon-asterisk'),
  EXCLAMATION_SIGN: goog.getCssName('icon-exclamation-sign'),
  GIFT: goog.getCssName('icon-gift'),
  LEAF: goog.getCssName('icon-leaf'),
  FIRE: goog.getCssName('icon-fire'),
  EYE_OPEN: goog.getCssName('icon-eye-open'),
  EYE_CLOSE: goog.getCssName('icon-eye-close'),
  WARNING_SIGN: goog.getCssName('icon-warning-sign'),
  PLANE: goog.getCssName('icon-plane'),
  CALENDAR: goog.getCssName('icon-calendar'),
  RANDOM: goog.getCssName('icon-random'),
  COMMENT: goog.getCssName('icon-comment'),
  MAGNET: goog.getCssName('icon-magnet'),
  CHEVRON_UP: goog.getCssName('icon-chevron-up'),
  CHEVRON_DOWN: goog.getCssName('icon-chevron-down'),
  RETWEET: goog.getCssName('icon-retweet'),
  SHOPPING_CART: goog.getCssName('icon-shopping-cart'),
  FOLDER_CLOSE: goog.getCssName('icon-folder-close'),
  FOLDER_OPEN: goog.getCssName('icon-folder-open'),
  RESIZE_VERTICAL: goog.getCssName('icon-resize-vertical'),
  RESIZE_HORIZONTAL: goog.getCssName('icon-resize-horizontal'),
  HDD: goog.getCssName('icon-hdd'),
  BULLHORN: goog.getCssName('icon-bullhorn'),
  BELL: goog.getCssName('icon-bell'),
  CERTIFICATE: goog.getCssName('icon-certificate'),
  THUMBS_UP: goog.getCssName('icon-thumbs-up'),
  THUMBS_DOWN: goog.getCssName('icon-thumbs-down'),
  HAND_RIGHT: goog.getCssName('icon-hand-right'),
  HAND_LEFT: goog.getCssName('icon-hand-left'),
  HAND_UP: goog.getCssName('icon-hand-up'),
  HAND_DOWN: goog.getCssName('icon-hand-down'),
  CIRCLE_ARROW_RIGHT: goog.getCssName('icon-circle-arrow-right'),
  CIRCLE_ARROW_LEFT: goog.getCssName('icon-circle-arrow-left'),
  CIRCLE_ARROW_UP: goog.getCssName('icon-circle-arrow-up'),
  CIRCLE_ARROW_DOWN: goog.getCssName('icon-circle-arrow-down'),
  GLOBE: goog.getCssName('icon-globe'),
  WRENCH: goog.getCssName('icon-wrench'),
  TASKS: goog.getCssName('icon-tasks'),
  FILTER: goog.getCssName('icon-filter'),
  BRIEFCASE: goog.getCssName('icon-briefcase'),
  FULLSCREEN: goog.getCssName('icon-fullscreen')
};
